name: rinemaa
description: A movie browsing app UI.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^1.2.1

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_rinema.png
    - assets/images/petaka.jpeg
    - assets/images/pabrik_gula.jpg
    - assets/images/komang.jpg
    - assets/images/petaka.jpeg
    - assets/images/pembantaian.jpg
